Traceback (most recent call last):
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/site-packages/nbclient/client.py", line 622, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/site-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/site-packages/jupyter_client/asynchronous/channels.py", line 48, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/site-packages/nbclient/client.py", line 841, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/site-packages/nbclient/client.py", line 646, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "/Volumes/storessd/Users/mariusmiron/opt/miniconda3/envs/startpack/lib/python3.7/site-packages/nbclient/client.py", line 697, in _async_handle_timeout
    "Cell execution timed out", timeout, cell
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 500 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['# Extracting features and writing in data.csv file in the segments folder', '#  each line in the data.csv file represents a sample with features and the class information as the last element', "data_file = os.path.join(tempdir,'data.csv')", 'file_count = 0', "with open(data_file, 'w') as writer:"]
...
['        selected_features = [features[descriptor] for descriptor in scalar_lowlevel_descriptors]', "        label = filename.split('/')[-1].split('.')[0].split('-')[0]", "        line2write = str(selected_features)[1:-1] + ',' + label + '\\n'", '        writer.write(line2write)', 'print("A total of ", file_count, "files processed")']
-------------------

